---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          adoptopenjdk/openjdk,
          fishtown-analytics/dbt,
          heroku/brew,
          homebrew/cask-versions,
          thoughtbot/formulae,
          weaveworks/tap,
          homebrew/cask-fonts,
        ]

    - name: 'Install core packages via brew casks'
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - bitwarden
        - discord
        - docker
        - google-chrome
        - microsoft-office
        - slack
        - zoom
        - spotify
        - obs
        - macs-fan-control
        - alacritty
        - font-fira-code-nerd-font
        - raindropio

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'autoconf',
          'coreutils',
          'htop',
          'mas',
          'libtool',
          'openssl',
          'pkg-config',
          'postgresql',
          'pipenv',
          'pyenv',
          'qemu',
          'readline',
          'sqlite',
          'tree',
          'nmap',
          'neovim',
          'unzip',
          'vim',
          'pipenv',
          'pyenv',
          'openconnect',
          'yarn',
          'zsh',
          'bitwarden-cli',
          'tmux',
          'nmap',
          'mysql',
          'neofetch',
          'bat',
          'ripgrep',
          'ruby',
          'sc-im',

        ]
        state: present
        update_homebrew: yes

    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: 'Load dotfile from bare git'
      include_role:
        name: lsevcik.dotfiles
      vars:
        dotfiles_repo: 'https://github.com/grantmca/.cfg'
        dotfiles_repo_local_destination: '$HOME/.cfg'
        dotfiles_repo_version: 'master'
