---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          adoptopenjdk/openjdk,
          fishtown-analytics/dbt,
          heroku/brew,
          homebrew/cask-versions,
          thoughtbot/formulae,
          weaveworks/tap,
        ]

    - name: 'Install core packages via brew casks'
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - bitwarden
        - discord
        - docker
        - google-chrome
        - microsoft-office
        - slack
        - zoom
        - spotify
        - obs
        - quicken
        - amethyst
        - macs-fan-control

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'autoconf',
          'coreutils',
          'htop',
          'mas',
          'libtool',
          'openssl',
          'pkg-config',
          'postgresql',
          'pipenv',
          'pyenv',
          'qemu',
          'readline',
          'sqlite',
          'tree',
          'nmap',
          'neovim',
          'unzip',
          'vim',
          'pipenv',
          'pyenv',
          'openconnect',
          'yarn',
          'zsh',
          'bitwarden-cli'
        ]
        state: present
        update_homebrew: yes
