---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          adoptopenjdk/openjdk,
          fishtown-analytics/dbt,
          heroku/brew,
          homebrew/cask-versions,
          thoughtbot/formulae,
          weaveworks/tap,
        ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - visual-studio-code
        - balenaetcher
        - discord
        - docker
        - sublime-text
        - google-chrome
        - microsoft-office
        - slack
        - telegram
        - zoom
        - autodesk-fusion360
        - spotify
        - obs
        - virtualbox
        - virtualbox-extension-pack
        - telegram-desktop
        - vlc
        - microsoft-remote-desktop
        - microsoft-teams	
        - quicken
        - rectangle
        - macs-fan-control
        - wireshark


    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'autoconf',
          'coreutils',
          'htop',
          'btop',
          'mas',
          'htop',
          'libtool',
          'openssl',
          'pkg-config',
          'postgresql',
          'pipenv',
          'pyenv',
          'qemu',
          'readline',
          'sqlite',
          'tree',
          'nmap',
          'unzip',
          'vim',
          'pipenv',
          'pyenv',
          'watchman',
          'openconnect',
          'xz',
          'yarn',
          'zlib',
          'zsh',
        ]
        state: present
        update_homebrew: yes


    # - name: Create a default VSCode configuration
    #   template:
    #     src: templates/vscode-settings.json.j2
    #     dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
    #     owner: "{{ lookup('env', 'USER') }}"
    #     force: yes

    - name: "Install from Mac app store"
      shell: mas install {{ item }}
      with_items:
        - 497799835 # xcode
        - 1274495053 # Microsoft To Do
        - 1444383602 #GoodNotes 5

    # Add something which ensures path is set here
    - name: Install VSCode extensions
      shell: code --install-extension {{ item }}
      with_items:
        - abusaidm.html-snippets
        - alexcvzz.vscode-sqlite
        - batisteo.vscode-django
        - ecmel.vscode-html-css
        - kiteco.kite
        - mohsen1.prettify-json
        - ms-azuretools.vscode-docker
        - ms-dotnettools.csharp
        - ms-python.python
        - ms-python.vscode-pylance
        - ms-toolsai.jupyter
        - ms-toolsai.jupyter-keymap
        - ms-toolsai.jupyter-renderers
        - ms-vscode-remote.remote-containers
        - ms-vscode.cpptools
        - mtxr.sqltools
        - ritwickdey.LiveServer
        - sidthesloth.html5-boilerplate
        - vscodevim.vim
