---
- hosts: localhost
  tasks:
    # - name: Install homebrew
    #   include_role:
    #     name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          adoptopenjdk/openjdk,
          fishtown-analytics/dbt,
          heroku/brew,
          homebrew/cask-versions,
          thoughtbot/formulae,
          weaveworks/tap,
          homebrew/cask-fonts,
          koekeishiya/formulae,
        ]

    - name: 'Install core packages via brew casks'
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - bitwarden
        - discord
        - docker
        - google-chrome
        - firefox
        - slack
        - zoom
        - spotify
        - macs-fan-control
        - wezterm
        - font-fira-code-nerd-font
        - raindropio
        - tigervnc-viewer
        - microsoft-outlook
        - gimp

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'autoconf',
          'coreutils',
          'htop',
          'mas',
          'libtool',
          'python',
          'openssl',
          'pkg-config',
          'postgresql',
          'pyenv',
          'readline',
          'sqlite',
          'jq',
          'tree',
          'nmap',
          'neovim',
          'unzip',
          'vim',
          'pipenv',
          'git',
          'pyenv',
          'openconnect',
          'yarn',
          'zsh',
          'bitwarden-cli',
          'tmux',
          'mysql',
          'neofetch',
          'rbenv',
          'spotify-tui',
          'yabai',
          'zsh',
          'skhd',
          'fzf',
          'bat',
          'ripgrep',
          'ruby',
          'sc-im',
        ]
        state: present
        update_homebrew: yes

    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: Load dotfile from bare git
      include_role:
        name: lsevcik.dotfiles
      vars:
        dotfiles_repo: "https://github.com/grantmca/.cfg"
        dotfiles_repo_version: "master"
        dotfiles_home: "{{ ansible_env.HOME }}"
        dotfiles_repo_local_destination: "{{ ansible_env.HOME }}/.cfg/"


    - name: Create symlink for .zshrc
      file:
        src: "{{ ansible_env.HOME }}/.zshrc"
        dest: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
        state: link
        force: yes

    - name: Create Developer directory
      file:
        path: "{{ ansible_env.HOME }}/Developer"
        state: directory
        mode: 0755

    - name: Clone TPM repository
      git:
        repo: 'https://github.com/tmux-plugins/tpm.git'
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
      tags: tmux  

    # - name: Clone Human Essentials
    #   git:
    #     repo: "https://github.com/grantmca/human-essentials"
    #     dest: "{{ ansible_env.HOME }}/Developer/human-essentials"
    #     version: main 

    - name: Clone Keyboard Config
      git:
        repo: "https://github.com/grantmca/zmk-config"
        dest: "{{ ansible_env.HOME }}/Developer/zmk-config"
        version: master 

    - name: Start Services For WM
      command: skhd --start-service && yabai --start-service

    # - name: Clone Playbook Setup
    #   git:
    #     repo: "https://github.com/grantmca/ansible-osx-setup"
    #     dest: "{{ ansible_env.HOME }}/Developer/ansible-osx-setup"
    #     version: master 
